apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sendgrid-binding.fullname" . }}
  labels:
    {{- include "sendgrid-binding.labels" . | nindent 4 }}
stringData:
  API_KEY: {{ required "'apiKey' is required" .Values.apiKey | quote }}
  FROM_EMAIL: {{ .Values.fromEmail | quote }}
