apiVersion: v1
kind: Secret
metadata:
  name: {{ include "twilio-binding.fullname" . }}
  labels:
    {{- include "twilio-binding.labels" . | nindent 4 }}
stringData:
  ACCOUNT_SID: {{ required "'accountSid' is required" .Values.accountSid | quote }}
  AUTH_TOKEN: {{ required "'authToken' is required" .Values.authToken | quote }}
  PHONE: {{ required "'phone' is required" .Values.phone | quote }}
