spring:
  profiles:
    active: "${ACTIVE_PROFILE:db-mongodb,sms-twilio,email-gmail}"
  graphql:
    websocket:
      path: /subscription
    schema:
      printer:
        enabled: true
    path: /graphql

  data:
    mongodb:
      uri: "${MONGODB_URI}"
      database: "${MONGODB_DATABASE}"
      username: "${MONGODB_USERNAME}"
      password: "${MONGODB_PASSWORD}"
      ca-cert-base64: "${MONGODB_CACERT_BASE64}"

twilio:
  accountSid: "${TWILIO_ACCOUNT_SID}"
  authToken: "${TWILIO_AUTH_TOKEN}"
  phoneNumber: "${TWILIO_PHONE}"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

logging:
  level:
    org.springframework.web: info
    org.springframework.http: info
    org.springframework.graphql: debug
    reactor.netty: debug
