apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mob-assist-api.fullname" . }}
  labels:
    {{- include "mob-assist-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mob-assist-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mob-assist-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mob-assist-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: mongodb-binding
              prefix: MONGODB_
            - secretRef:
                name: twilio-binding
              prefix: TWILIO_
            - secretRef:
                name: sendgrid-binding
              prefix: SENDGRID_
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-config
                  key: uri
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb-config
                  key: name
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-config
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-config
                  key: password
            - name: MONGODB_CACERT_BASE64
              valueFrom:
                secretKeyRef:
                  name: mongodb-config
                  key: certificate_base64
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: twilio-config
                  key: account-sid
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twilio-config
                  key: auth-token
            - name: TWILIO_PHONE
              valueFrom:
                secretKeyRef:
                  name: twilio-config
                  key: phone
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/info
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
