{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "mob-assist-api.name" . }}
  labels:
    {{ include "mob-assist-api.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "mob-assist-api.fullname" . }}
    weight: 100
{{- end }}