apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-binding.fullname" . }}
  labels:
    {{- include "mongodb-binding.labels" . | nindent 4 }}
stringData:
  CONNECT_STRING: {{ required "'connectString' is required" .Values.connectString | quote }}
  HOST: {{ required "'host' is required" .Values.host | quote }}
  PORT: {{ required "'port' is required" .Values.port | quote }}
  USERNAME: {{ required "'username' is required" .Values.username | quote }}
  PASSWORD: {{ required "'password' is required" .Values.password | quote }}
  DATABASE: {{ required "'database' is required" .Values.database | quote }}
